spring:
  application:
    name: asuna
  datasource:
    url: jdbc:mysql://rm-bp1me825ef7cdy71o125010.mysql.rds.aliyuncs.com/asuna
    username: tj
    password: lujunxian
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

remote-call:
  pm25:
    url: http://www.pm25.in
    app-key: 5j1znBVAsnSf5xQyNQyq

