spring:
  application:
    name: asuna
  datasource:
    url: jdbc:mysql://rm-bp1me825ef7cdy71ogo.mysql.rds.aliyuncs.com/asuna_test
    username: tj
    password: lujunxian
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

remote-call:
  pm25:
    url: http://www.pm25.in
    app-key: 5j1znBVAsnSf5xQyNQyq

megvii:
  face-plus:
    host: https://api-cn.faceplusplus.com
    api-key: ggvJXa3aYHYw1gOEXf-Jz7TlLl_j7b_V
    api-secret: e-PMwucjdElZCRq9pInFK5BbmCpPBzop

